# frozen_string_literal: true

module MPK
  module OutputAdapters
    class Loon < Base
      SUPPORTED_PROXIES = %w[ss vmess trojan].freeze
      SUPPORTED_GROUP_TYPES = %w[select url-test fallback].freeze

      def id = 'loon'
      def extension = '.conf'

      def render(policy)
        mapping!(policy)
        require_no_proxy_providers!(policy)
        proxies = proxy_list(policy)
        proxies.each { |proxy| supported_proxy!(proxy, SUPPORTED_PROXIES) }
        validate_group_references!(policy)
        validate_rules!(policy)
        validate_group_types!(policy)

        lines = ['# Generated by mihomo-policy-kit; strict V0.4 Loon adapter.', '[General]', '', '[Proxy]']
        lines.concat(proxies.map { |proxy| render_proxy(proxy) })
        lines += ['', '[Proxy Group]']
        lines.concat(Array(policy['proxy-groups']).map { |group| render_group(group) })
        lines += ['', '[Rule]']
        lines.concat(Array(policy['rules']).map { |rule| render_rule(rule) })
        lines.join("\n") + "\n"
      end

      def validate(content)
        validate_conf!(content)
      end

      def write(content, output_path)
        validate(content)
        super
      end

      private

      def render_proxy(proxy)
        type = proxy['type'].to_s.downcase
        require_fields!(proxy, 'server', 'port')
        case type
        when 'ss'
          reject_unmapped_fields!(proxy, %w[name type server port cipher password udp])
          require_fields!(proxy, 'cipher', 'password')
          "#{proxy['name']} = Shadowsocks,#{proxy['server']},#{proxy['port']},#{proxy['cipher']},#{conf_value(proxy['password'])},udp=#{proxy.fetch('udp', true) ? 'true' : 'false'}"
        when 'vmess'
          reject_unmapped_fields!(proxy, %w[name type server port uuid cipher alterId network tls sni servername ws-opts udp skip-cert-verify])
          require_fields!(proxy, 'uuid')
          transport = proxy['network'].to_s.empty? ? 'tcp' : proxy['network'].to_s
          raise Error, 'loon adapter only supports VMess tcp or ws transport' unless %w[tcp ws].include?(transport)
          raise Error, 'loon adapter VMess ws-opts require ws transport' if transport != 'ws' && proxy.key?('ws-opts')
          parts = ["#{proxy['name']} = vmess", proxy['server'], proxy['port'], proxy.fetch('cipher', 'auto'), conf_value(proxy['uuid']), "transport=#{transport}", "alterId=#{proxy.fetch('alterId', 0)}", "over-tls=#{proxy['tls'] ? 'true' : 'false'}", "udp=#{proxy.fetch('udp', true) ? 'true' : 'false'}"]
          if transport == 'ws'
            opts = proxy['ws-opts'].is_a?(Hash) ? proxy['ws-opts'] : {}
            parts << "path=#{opts.fetch('path', '/')}"
            host = opts.dig('headers', 'Host')
            parts << "host=#{host}" unless host.to_s.empty?
          end
          sni = proxy['servername'] || proxy['sni']
          parts << "sni=#{sni}" unless sni.to_s.empty?
          parts << "skip-cert-verify=#{proxy['skip-cert-verify'] ? 'true' : 'false'}" if proxy.key?('skip-cert-verify')
          parts.join(',')
        when 'trojan'
          reject_unmapped_fields!(proxy, %w[name type server port password network tls sni servername ws-opts udp skip-cert-verify])
          require_fields!(proxy, 'password')
          transport = proxy['network'].to_s.empty? ? 'tcp' : proxy['network'].to_s
          raise Error, 'loon adapter only supports Trojan tcp or ws transport' unless %w[tcp ws].include?(transport)
          raise Error, 'loon adapter Trojan cannot disable TLS' if proxy.key?('tls') && !proxy['tls']
          raise Error, 'loon adapter Trojan ws-opts require ws transport' if transport != 'ws' && proxy.key?('ws-opts')
          parts = ["#{proxy['name']} = trojan", proxy['server'], proxy['port'], conf_value(proxy['password'])]
          if transport == 'ws'
            opts = proxy['ws-opts'].is_a?(Hash) ? proxy['ws-opts'] : {}
            parts << 'transport=ws'
            parts << "path=#{opts.fetch('path', '/')}"
            host = opts.dig('headers', 'Host')
            parts << "host=#{host}" unless host.to_s.empty?
          end
          sni = proxy['servername'] || proxy['sni']
          parts << "sni=#{sni}" unless sni.to_s.empty?
          parts << "skip-cert-verify=#{proxy['skip-cert-verify'] ? 'true' : 'false'}" if proxy.key?('skip-cert-verify')
          parts << "udp=#{proxy.fetch('udp', true) ? 'true' : 'false'}"
          parts.join(',')
        end
      end

      def validate_group_types!(policy)
        Array(policy['proxy-groups']).each do |group|
          type = group['type'].to_s
          next if SUPPORTED_GROUP_TYPES.include?(type)
          raise Error, "loon adapter does not support proxy group type: #{type}"
        end
      end

      def render_group(group)
        members = Array(group['proxies']).map { |item| conf_value(item) }
        "#{group['name']} = #{group['type']},#{members.join(',')}"
      end

      def render_rule(rule)
        parts = rule_parts(rule)
        return "FINAL,#{parts[1]}" if parts.first.to_s.upcase == 'MATCH'

        parts.join(',')
      end

      def validate_conf!(content)
        %w[[General] [Proxy] [Proxy\ Group] [Rule]].each do |section|
          raise Error, "loon adapter output missing #{section} section" unless content.include?(section)
        end
        raise Error, 'loon adapter output has no FINAL rule' unless content.each_line.any? { |line| line.start_with?('FINAL,') }
      end
    end
  end
end
