# frozen_string_literal: true

module MPK
  module OutputAdapters
    class Surge < Base
      SUPPORTED_PROXIES = %w[ss vmess trojan].freeze
      SUPPORTED_GROUP_TYPES = %w[select url-test fallback].freeze

      def id = 'surge'
      def extension = '.conf'

      def render(policy)
        mapping!(policy)
        require_no_proxy_providers!(policy)
        proxies = proxy_list(policy)
        proxies.each { |proxy| supported_proxy!(proxy, SUPPORTED_PROXIES) }
        validate_group_references!(policy)
        validate_rules!(policy)
        validate_group_types!(policy)

        lines = ['# Generated by mihomo-policy-kit; strict V0.4 Surge adapter.', '[General]', 'loglevel = notify', '', '[Proxy]']
        lines.concat(proxies.map { |proxy| render_proxy(proxy) })
        lines += ['', '[Proxy Group]']
        lines.concat(Array(policy['proxy-groups']).map { |group| render_group(group) })
        lines += ['', '[Rule]']
        lines.concat(Array(policy['rules']).map { |rule| render_rule(rule) })
        lines.join("\n") + "\n"
      end

      def validate(content)
        validate_conf!(content)
      end

      def write(content, output_path)
        validate(content)
        super
      end

      private

      def render_proxy(proxy)
        type = proxy['type'].to_s.downcase
        require_fields!(proxy, 'server', 'port')
        case type
        when 'ss'
          reject_unmapped_fields!(proxy, %w[name type server port cipher password udp])
          require_fields!(proxy, 'cipher', 'password')
          raise Error, 'surge adapter does not support disabled Shadowsocks UDP relay' if proxy.key?('udp') && !proxy['udp']
          "#{proxy['name']} = ss, #{proxy['server']}, #{proxy['port']}, encrypt-method=#{proxy['cipher']}, password=#{conf_value(proxy['password'])}, udp-relay=true"
        when 'vmess'
          reject_unmapped_fields!(proxy, %w[name type server port uuid cipher alterId network tls sni servername ws-opts udp skip-cert-verify])
          require_fields!(proxy, 'uuid')
          transport = proxy['network'].to_s.empty? ? 'tcp' : proxy['network'].to_s
          raise Error, 'surge adapter only supports VMess tcp or ws transport' unless %w[tcp ws].include?(transport)
          raise Error, 'surge adapter VMess ws-opts require ws transport' if transport != 'ws' && proxy.key?('ws-opts')
          raise Error, 'surge adapter does not support disabled VMess UDP relay' if proxy.key?('udp') && !proxy['udp']
          parts = ["#{proxy['name']} = vmess", proxy['server'], proxy['port'], "username=#{proxy['uuid']}"]
          parts << "encrypt-method=#{proxy['cipher']}" unless proxy['cipher'].to_s.empty? || proxy['cipher'].to_s == 'auto'
          parts << 'tls=true' if proxy['tls']
          if transport == 'ws'
            opts = proxy['ws-opts'].is_a?(Hash) ? proxy['ws-opts'] : {}
            parts << 'ws=true'
            parts << "ws-path=#{opts.fetch('path', '/')}"
            host = opts.dig('headers', 'Host')
            parts << "ws-headers=Host:#{host}" unless host.to_s.empty?
          end
          sni = proxy['servername'] || proxy['sni']
          parts << "sni=#{sni}" unless sni.to_s.empty?
          parts << "skip-cert-verify=#{proxy['skip-cert-verify'] ? 'true' : 'false'}" if proxy.key?('skip-cert-verify')
          # alterId==0 (Mihomo default) means AEAD; alterId>0 means legacy.
          # Surge's vmess-aead flag maps directly, so emit it explicitly rather
          # than silently dropping the AEAD decision.
          alter_id = proxy.fetch('alterId', 0).to_i
          parts << (alter_id.zero? ? 'vmess-aead=true' : 'vmess-aead=false')
          parts.join(', ')
        when 'trojan'
          reject_unmapped_fields!(proxy, %w[name type server port password network tls sni servername ws-opts udp skip-cert-verify])
          require_fields!(proxy, 'password')
          transport = proxy['network'].to_s.empty? ? 'tcp' : proxy['network'].to_s
          raise Error, 'surge adapter only supports Trojan tcp or ws transport' unless %w[tcp ws].include?(transport)
          raise Error, 'surge adapter Trojan cannot disable TLS' if proxy.key?('tls') && !proxy['tls']
          raise Error, 'surge adapter Trojan ws-opts require ws transport' if transport != 'ws' && proxy.key?('ws-opts')
          raise Error, 'surge adapter does not support disabled Trojan UDP relay' if proxy.key?('udp') && !proxy['udp']
          parts = ["#{proxy['name']} = trojan", proxy['server'], proxy['port'], "password=#{conf_value(proxy['password'])}"]
          if transport == 'ws'
            opts = proxy['ws-opts'].is_a?(Hash) ? proxy['ws-opts'] : {}
            parts << 'ws=true'
            parts << "ws-path=#{opts.fetch('path', '/')}"
            host = opts.dig('headers', 'Host')
            parts << "ws-headers=Host:#{host}" unless host.to_s.empty?
          end
          sni = proxy['servername'] || proxy['sni']
          parts << "sni=#{sni}" unless sni.to_s.empty?
          parts << "skip-cert-verify=#{proxy['skip-cert-verify'] ? 'true' : 'false'}" if proxy.key?('skip-cert-verify')
          parts.join(', ')
        end
      end

      def validate_group_types!(policy)
        Array(policy['proxy-groups']).each do |group|
          type = group['type'].to_s
          next if SUPPORTED_GROUP_TYPES.include?(type)
          raise Error, "surge adapter does not support proxy group type: #{type}"
        end
      end

      def render_group(group)
        type = group['type'].to_s
        members = Array(group['proxies']).map { |item| conf_value(item) }
        line = "#{group['name']} = #{type}, #{members.join(', ')}"
        params = group_params(group, type)
        params.empty? ? line : "#{line}, #{params.join(', ')}"
      end

      def group_params(group, type)
        case type
        when 'select'
          reject_unmapped_group_fields!(group, %w[name type proxies])
          []
        when 'url-test'
          reject_unmapped_group_fields!(group, %w[name type proxies url interval tolerance lazy])
          group_param_parts(group, %w[url interval tolerance lazy])
        when 'fallback'
          reject_unmapped_group_fields!(group, %w[name type proxies url interval lazy])
          group_param_parts(group, %w[url interval lazy])
        else
          []
        end
      end

      def render_rule(rule)
        parts = rule_parts(rule)
        return "FINAL,#{parts[1]}" if parts.first.to_s.upcase == 'MATCH'

        parts.join(',')
      end

      def validate_conf!(content)
        %w[[General] [Proxy] [Proxy\ Group] [Rule]].each do |section|
          raise Error, "surge adapter output missing #{section} section" unless content.include?(section)
        end
        raise Error, 'surge adapter output has no FINAL rule' unless content.each_line.any? { |line| line.start_with?('FINAL,') }
      end
    end
  end
end
